---
title: "Create Supplementary Information"
author: "Beni Stocker"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rbeni)
```

## Testing $S_0$ diagnosing

As testing sites, use sites from the rooting depth dataset (RSIP).

```{r cars}
df_sites <- read_csv("data/df_sites_rsip.csv")
```

Extract information of S0 diagnostic for given locations.

Sample 30 sites out of the 1705.
```{r}
set.seed(1982)
use_biomes <- df_sites %>% 
  group_by(biome) %>% 
  summarise(n = n()) %>% 
  dplyr::filter(n >=5 & !is.na(biome)) %>% 
  pull(biome)

df_sites_sampled <- df_sites %>% 
  dplyr::filter(biome %in% use_biomes) %>% 
  group_by(biome) %>% 
  group_split() %>% 
  purrr::map(~sample_n(., 3)) %>% 
  bind_rows()
```

Plot sites on map
```{r}
library(jcolors)
nbiomes <- df_sites_sampled %>% 
  drop_na(biome_name) %>%
  pull(biome_name) %>% 
  unique() %>% 
  length()

plot_map_simpl() +
  geom_point(data = df_sites_sampled,
             aes(x = lon, y = lat, color = biome_name)) +
  # scale_color_jcolors(palette = "pal8")
  # scale_color_brewer(palette = "Paired")
  scale_colour_manual(values = myjcolors(nbiomes), name = "Biome name")
```

Determine all chunks (latitudinal bands)
```{r}
get_ilon <- function(lon){
  lon_hires <- seq(-179.975, 179.975, by = 0.05)
  ilon <- which.min(abs(lon - lon_hires))
  return(ilon)  
}

df_sites_sampled <- df_sites_sampled %>% 
  mutate(ilon = purrr::map_dbl(lon, ~get_ilon(.)))
```

Get all data for chunks.
```{r}
source("R/calc_cwd_et0_byilon.R")
system("mkdir -p ~/mct/data/df_cwd_et0_3")
filn <- "data/df_test_cwd_et0.rds"

if (!file.exists(filn)){
  df <- df_sites_sampled %>% 
    slice(1) %>% 
    mutate(out = purrr::map2(ilon, 
                             lat, 
                             ~calc_cwd_et0_byilon(.x, 
                                                  drop_data = FALSE, 
                                                  dirn = "~/mct/data/df_cwd_et0_3/", 
                                                  verbose = FALSE, 
                                                  overwrite = TRUE, 
                                                  siteinfo = NULL, 
                                                  do_plot = TRUE, 
                                                  use_lat = .y
                                                  )))
  
  saveRDS(df, file = filn)
} else {
  df <- readRDS(filn)
}
```

Visualise
```{r}
# myplot <- function(n, df){
#   print(n)  
#   df$out[[n]]$gg_fet
# }
# purrr::map(as.list(seq(36)), ~myplot(., df))

## example for no decline
gg1 <- df$out[[2]]$gg_fet[[1]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

## example for S0 diagnosed (9, 34, 21)
gg2 <- df$out[[34]]$gg_fet[[1]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

gg3 <- df$out[[21]]$gg_fet[[1]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

## example for flattening
gg4 <- df$out[[31]]$gg_fet[[1]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

cowplot::plot_grid(gg1, gg4, gg2, gg3, nrow = 2, labels = c('a', 'b', 'c', 'd'))
ggsave("fig/plot_test_s0_diag.pdf", width = 12, height = 8)
ggsave("fig/plot_test_s0_diag.png", width = 12, height = 8)
```

Visualise
```{r}
tmp <- df %>% 
  select(-lon, -lat) %>% 
  unnest(out)
  mutate(gg = purrr::map(out, ~pull(slice(., 1), gg_fet)),
         cwd_lue0_fet = purrr::map_dbl(out, ~pull(., cwd_lue0_fet)))
  
## example for no decline
gg1 <- tmp$gg_fet[[2]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

## example for S0 diagnosed (9, 34, 21)
gg2 <- tmp$gg_fet[[32]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()

gg3 <- tmp$gg_fet[[21]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()  
  
## example for flattening
gg4 <- tmp$gg_fet[[29]] +
  labs(title = NULL, y = "EF (unitless)") +
  theme_classic()  

cowplot::plot_grid(gg1, gg4, gg2, gg3, nrow = 2, labels = c('a', 'b', 'c', 'd'))

## retain selected
tmp2 <- tmp %>% 
  slice(c(2, 32, 21, 29))

# ## s_def diagnostic
# df$out[[1]]$gg_fet
# 
# ## water balance time series
# df$out[[1]]$data[[1]] %>% 
#   ggplot(aes(time, bal)) + 
#   geom_line()
# 
# df$out[[1]]$data[[1]] %>% 
#   ggplot(aes(deficit, fet)) + 
#   geom_point()
# 
# df$out[[1]]$data[[1]] %>% 
#   ggplot(aes(NR, et)) + 
#   geom_point() +
#   geom_smooth(method = "lm")
```

Plot the same from the model outputs.
```{r}
# ## determine chunk used for the four sites in tmp2
# df_sites_ichunk <- read_csv("data/df_sites_rsip.csv") %>%
#   mutate(idx = 1:n()) %>%
#   mutate(chunk = rep(1:as.integer(50),
#                      each = (nrow(.)/as.integer(50)), len = nrow(.)))
# 
# tmp2 <- tmp2 %>% 
#   left_join(
#     df_sites_ichunk %>% 
#       select(lon, lat, Dr, chunk)
#   )

read_myfile <- function(ichunk, use_whc){
  path <- "./data/out_rsofun_cwdx/"
  filename <- file.path(path, paste0("out_rsofun_cwdx_whc_", as.character(use_whc), "_ichunk_", as.character(ichunk), ".rds"))
  if (file.exists(filename)){
    df <- readRDS(filename)
    return(df)
  } else {
    return(tibble())
  }
}

set.seed(1982)
df_rsofun <- purrr::map_dfr(
      as.list(sample(seq(50), 3)),
      ~read_myfile(., "200")
      ) %>% 
      mutate(setup = "whc_200")

# ## example of S0 detected
# df_rsofun$out_cwd_lue0[[20]]$gg +
#   geom_vline(xintercept = df_rsofun$whc[20])

```

```{r}
purrr::map(seq(1:30), ~{print(df_rsofun$out_cwd_lue0[[.]]$gg)})

```

## Magnitudes of EF

Read FLUXNET2015 data
```{r}
library(ingestr)
ddf_fluxnet <- ingest(
  siteinfo  = siteinfo_fluxnet2015,
  source    = "fluxnet",
  getvars   = list(netrad = "NETRAD", et = "LE_F_MDS"),
  dir       = "~/data/FLUXNET-2015_Tier1/20191024/DD/",  # adjust this with your local path
  settings  = list(
    getswc       = FALSE,
    filter_ntdt  = FALSE,
    remove_neg   = FALSE,
    threshold_LE = 0.8
    ),
  timescale = "d",
  verbose = TRUE
  )

## take 95% quantile of EF by site
tmp <- ddf_fluxnet %>% 
  mutate(data = purrr::map(data, ~mutate(., ef = remove_outliers(et/netrad)))) %>% 
  unnest(data) %>% 
  group_by(sitename) %>% 
  summarise(ef_q95 = quantile(ef, probs = 0.90, na.rm = TRUE))

tmp %>% 
  ggplot(aes(ef_q95, ..count..)) +
  geom_histogram() + 
  theme_classic() +
  labs(x = "Maximum evaporative fraction (unitless)", y = "Count") +
  xlim(0, 2) +
  geom_vline(xintercept = 1.0, linetype = "dotted")
ggsave("fig/max_ef_fluxnet2015.pdf", width = 6, height = 4)
ggsave("fig/max_ef_fluxnet2015.png", width = 6, height = 4)
```


## CWD demo

```{r}
source("R/test_cwd_tseries.R")
# load("~/mct/data/df_cwdx/df_cwdx_ilon_5000.RData")

idxc <- 1
idxa <- 500
idxb <- 300 # 100

gg1 <- test_cwd_tseries(
  df$out_mct[[idxa]]$mct, 
  sitename = NA, 
  filter_years = NA, 
  title = paste0(as.character(df$lon[idxa]), "°E, ", as.character(df$lat[idxa]), "°N")
  )

gg2 <- test_cwd_tseries(
  df$out_mct[[idxb]]$mct, 
  sitename = NA, 
  filter_years = NA, 
  title = paste0(as.character(df$lon[idxb]), "°E, ", as.character(df$lat[idxb]), "°N")
  )

gg3 <- test_cwd_tseries(
  df$out_mct[[idxc]]$mct, 
  sitename = NA, 
  filter_years = NA, 
  title = paste0(as.character(df$lon[idxc]), "°E, ", as.character(df$lat[idxc]), "°N")
  )

df_sites <- tibble(
  sitename = c("a", "b", "c"),
  lon = c(df$lon[idxa], df$lon[idxb], df$lon[idxc]),
  lat = c(df$lat[idxa], df$lat[idxb], df$lat[idxc])
)

library(rbeni)
library(ggrepel)

gg0 <- plot_map_simpl() +
  geom_text(data = df_sites, aes(lon, lat, label = sitename), color = "red")

cowplot::plot_grid(gg0, gg1, gg2, gg3, labels = c("", "a", "b", "c"), nrow = 2)
ggsave("fig/cwd_tseries.pdf", width = 12, height = 7)
ggsave("fig/cwd_tseries.png", width = 12, height = 7)
```

