---
title: "Re-scale ET"
author: "Beni Stocker"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

## The problem 

In some very dry pixels, ET tends to be so high that a cumulative water deficit "runaway" occurs.
```{r}
## CWDX data
#source("rscript_collect_cwdx.R")
load("data/df_cwdx_10_20_40.RData") # loads 'df'

## spain
df %>% 
  dplyr::filter(lon > -10 & lon < 5 & lat > 35 & lat < 45) %>% 
  plot_map3(varnam = "cwdx20", lonmin = -10, lonmax = 5, latmin = 35, latmax = 45)

## andalusia
df %>% 
  dplyr::filter(lon > -7 & lon < -4 & lat > 36 & lat < 37.5) %>% 
  plot_map3(varnam = "cwdx20", lonmin = -7, lonmax = -4, latmin = 36, latmax = 37.5)

## take example of missing cells in andalusia:
df_test <- df %>% 
  dplyr::filter(lon > -7 & lon < -4 & lat > 36 & lat < 37.5) %>% 
  dplyr::filter(is.na(cwdx20)) %>% 
  slice(1)

lon <- df_test$lon  # is -6.225
uselat <- df_test$lat  # is 37.025
lon_hires <- seq(-179.975, 179.975, by = 0.05)
ilon_hires <- which.min(abs(lon_hires - -6.225))

dirn <- "~/mct/data/df_bal/"
filn <- paste0("df_bal_ilon_", ilon_hires, ".RData")
load(paste0(dirn, filn)) # loads 'df'

## determine CWD and events
tmp <- df %>%
  dplyr::filter(lat == uselat)
  
tmp$data[[1]] %>% 
  mutate(cumbal = cumsum(bal)) %>% 
  ggplot(aes(x = time, y = cumbal)) + 
  geom_line()  
  
  # dplyr::mutate(
  #   out_mct = purrr::map(
  #     data,
  #     ~get_plantwhc_mct_bysite(
  #       .,
  #       varname_wbal = "bal",
  #       varname_date = "time",
  #       thresh_terminate = 0.0,
  #       thresh_drop = 0.9,
  #       fittype = "Gumbel"))
  # )
```

## The solution

Check for systemaic bias in ALEXI-ET at FLUXNET sites.

Get ALEXI-ET estimates (originals, in W m-2) around FLUXNET sites.
```{r}
library(ingestr)

load_alexi_et_mm_byilon <- function(ilon_hires, lat){
  load(paste("~/mct/data/df_alexi_et_mm/df_alexi_et_mm_ilon_", ilon_hires, ".RData"))  # loads df_alexi
  lat_hires <- pull(df_alexi, lat)
  idx <- which.min(abs(lat - lat_hires))
  df_alexi %>% 
    ungroup() %>% 
    slice(idx)
}

lon_hires <- seq(-179.975, 179.975, by = 0.05)

## use sites based on Manuela Balzarolo's selection.
usesites <- read_csv("~/rsvi/data/sites2.csv")

df_fluxnet <- siteinfo_fluxnet2015 %>% 
  rowwise() %>% 
  dplyr::filter(sitename %in% usesites$sitename) %>% 
  mutate(ilon_hires = which.min(abs(lon_hires - lon)))

save(df_fluxnet, file = "data/df_fluxnet.Rdata")

siteinfo_fluxnet2015 <- siteinfo_fluxnet2015 %>% 
  mutate(data = purrr::map2(ilon_hires, lat, ~load_alexi_et_mm_byilon(.x, .y)))


## example

```

