---
title: "rsofun at RSIP sites"
author: "Beni Stocker"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rsofun)
library(ingestr)
library(rbeni)
```

## Get sites

```{r cars}
df <- read_csv("~/data/rootingdepth/rsip/RSIP_Analysis_sheet_210409.csv") %>%      # previously done with "data/RSIP_Analysis_sheet.csv"
# df <- read_csv("~/data/rootingdepth/rsip/RSIP_Analysis_sheet_210721.csv") %>% 
  rename(lon = Long, lat = Lat) %>% 
  rowid_to_column(var = "id") %>% 
  
  ## problem: some have a reference error
  dplyr::filter(lon != "#REF!") %>% 
  mutate(lon = as.numeric(lon), lat = as.numeric(lat), 
         Dr = as.numeric(Dr),
         wtd = as.numeric(Water_Table_Depth_Fan))
  
print(paste("Total number of entries:", nrow(df)))
```

Add model results.
```{r}
df <- extract_nc(df %>% dplyr::select(id, lon, lat), "data/zroot_cwd80.nc") %>% 
  unnest(data) %>% 
  rename(zroot_cwdx80 = V1) %>% 
  mutate(zroot_cwdx80 = zroot_cwdx80 / 1000) %>% 
  right_join(df, by = c("lon", "lat", "id"))
```

1705 distinct sites based on lon and lat info.
```{r}
df_sites <- df %>% 
  mutate(sitename = paste0("i_", as.character(lon), "_", as.character(lat))) %>% 
  group_by(sitename) %>% 
  summarise(Dr = mean(Dr, na.rm = TRUE), zroot_cwdx80 = mean(zroot_cwdx80, na.rm = TRUE), wtd = mean(wtd, na.rm = TRUE))

## add WWF biome info
df_wwf_sites <- ingest(
  df %>% 
    distinct(lon, lat) %>% 
    mutate(sitename = paste0("i_", as.character(lon), "_", as.character(lat))),
  source = "wwf",
  dir = "~/data/biomes/wwf_ecoregions/official/",
  settings = list(layer = "wwf_terr_ecos")
  )%>% 
  mutate(data = purrr::map(data, ~slice(., 1))) %>% 
  unnest(data)

df_sites <- df_sites %>% 
  left_join(
    df_wwf_sites %>% 
      dplyr::select(sitename, biome = BIOME, biome_name = BIOME_NAME),
    by = "sitename"
  )

df_sites <- df_sites %>% 
  separate(sitename, c("prefix", "lon", "lat"), sep = "_") %>% 
  dplyr::select(-prefix) %>% 
  mutate(sitename = paste0("i_", 1:nrow(.))) %>% 
  mutate(lon = as.numeric(lon), lat = as.numeric(lat)) %>%
  mutate(
    year_start = 1989,
    year_end = 2018
  )

# add elevation data
if(grepl('eu-', Sys.info()['nodename'])){
  r <- raster::raster("~/data/etopo/ETOPO1_Bed_g_geotiff.tif")
}

# grab elev data
s <- st_as_sf(
  df,
  coords = c("lon","lat"),
  crs = 4326)
df$elv <- raster::extract(r, s)
df <- df %>%
  mutate(
    elv = ifelse(elv < 0, 0, elv)
  )

write_csv(df_sites, file = "data/df_sites_rsip.csv")  
```

## Get forcing data

Use `submit_forcing_rsip.sh` to run `rscript_forcing_rsip.R`. This saves files in subdirectory `"./data/forcing_rsip/"`.

## Run rsofun

Do this with branch `mct` where liquid water infiltration into the soil is written to output.
```{r}
source("R/process_pmodel.R")
df_forcing <- readRDS("./data/forcing_rsip/pmodel_drivers_1.rds")

df_output <- process_pmodel(
  "./data/forcing_rsip/pmodel_drivers_1.rds",
  agg = FALSE)
```


## Diagnose S0

```{r}
## AET/PET vs. time
df_output <- df_output %>% 
  dplyr::filter(sitename == "i_1") %>% 
  rename(aet = transp) %>% 
  mutate(ef = aet / pet)

df_output %>% 
  ggplot(aes(date, ef)) + 
  geom_line()

## AET/PET vs. wcont
df_output %>% 
  ggplot(aes(wscal, ef)) + 
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_vline(xintercept = 0, linetype = "dotted")
```
Get CWD time series. Infiltration is `infilt`. 
```{r}
library(segmented)
source("R/get_plantwhc_mct_bysite.R")
source("R/mct2.R")
source("R/calc_cwd_lue0_v2.R")

list_output <- df_output %>%
  group_by(sitename) %>%
  group_split() %>% 
  purrr::map(., ~mutate(., 
                        wbal = infilt - transp,
                        ef = transp / pet))

##------------------------------------------
## apply mct function to get CWD
##------------------------------------------
out_mct <- mct(list_output[[1]], 
               varname_wbal = "wbal", 
               varname_date = "date" 
               )

out_mct$df %>% 
  ggplot(aes(deficit, ef)) +
  geom_point(alpha = 0.3) +
  geom_vline(xintercept = df_forcing$site_info[[1]]$whc) +
  geom_hline(yintercept = 0, linetype = "dotted")
```

```{r}
##------------------------------------------
## fit extreme value statistics  
##------------------------------------------
gumbi <- get_plantwhc_mct_bysite(list_output[[1]] %>% 
                                   dplyr::select(-date_start, -date_end),   
                                 varname_wbal = "wbal", 
                                 varname_date = "date" 
                                 )

use_return_period <- 80
```

```{r}
out <- calc_cwd_lue0(out_mct$df, 
              out_mct$inst, 
              "ef", 
              do_plot = TRUE, 
              verbose = TRUE
              )

out$gg +
  geom_vline(xintercept = df_forcing$site_info[[1]]$whc) +
  geom_vline(xintercept = gumbi$df_return %>% 
                            filter(return_period == use_return_period) %>% 
                            pull(return_level),
             color = "royalblue"
             )
```